import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import Lesson from './Lesson';

import axios from 'axios';

class Lessons extends Component {
  constructor(props) {
    super(props);

    this.deleteLesson = this.deleteLesson.bind(this);

    this.state = { lessons: [] };
  }  
   
  // Retrieve all lessons from database
  componentDidMount() {
    axios.get('http://localhost:5000/lessons')
      .then(res => {
        this.setState({ lessons: res.data});
      })
      .catch((error) => {
        console.log(error);
      });
  }

  // deleteLesson - removes a single lesson from the database
  deleteLesson(id) {
    axios.delete(`http://localhost:5000/lessons/${id}`)
      .then(res => console.log(res.data));

      // Remove lesson from DOM - _id refers to autogenerated id assigned by MongoDB
      this.setState({
        lessons: this.state.lessons.filter(el => el._id !== id)
      });
  }

  // lessonList - selects all lessons from database for display
  

  render() {
    return (
      <div>
        <h1 className="text-center mx-auto">Lessons Index</h1>
        <div className="row justify-content-center">
          {this.state.lessons.map(lesson => (
            <Lesson lesson={lesson} deleteLesson={this.deleteLesson} key={lesson._id} />
          ))}
        </div>
      </div>
    )
  }
}

export default Lessons;