import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import Student from './Student';

import axios from 'axios';

class Students extends Component {
  constructor(props) {
    super(props);

    this.deleteStudent = this.deleteStudent.bind(this);

    this.state = { students: [] };
  }  
   
  // Retrieve all students from database
  componentDidMount() {
    axios.get('http://localhost:5000/students')
      .then(res => {
        this.setState({ students: res.data});
      })
      .catch((error) => {
        console.log(error);
      });
  }

  // deleteStudent - removes a student from the database
  deleteStudent(id) {
    axios.delete(`http://localhost:5000/students/${id}`)
      .then(res => console.log(res.data));

      // Remove student element from DOM - _id refers to autogenerated id assigned by MongoDB
      this.setState({
        students: this.state.students.filter(el => el._id !== id)
      });
  }

  // studentList - selects all lessons from database for display
  

  render() {
    return (
      <div>
        <h1 className="text-center mx-auto">Active Students</h1>
        <div className="row justify-content-center">
          {this.state.students.map(student => (
            <Student student={student} deleteStudent={this.deleteStudent} key={student._id} />
          ))}
        </div>
      </div>
    )
  }
}

export default Students;